CREATE TABLE [data] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[sid] INTEGER  NOT NULL,
[eid] INTEGER  NOT NULL,
[entry] INTEGER  NOT NULL,
[ctime] TIME  NOT NULL,
[tag] VARCHAR(20)  NOT NULL,
[weight] INTEGER  NOT NULL,
[smoothed] INTEGER  NOT NULL,
[note] VARCHAR(40)  NOT NULL
);

CREATE TABLE [event] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[sid] INTEGER  NOT NULL,
[sdate] DATE  NOT NULL,
[stime] TIME  NOT NULL,
[note] VARCHAR(80)  NOT NULL,
[source] INTEGER  NOT NULL,
[flags] INTEGER DEFAULT '0' NOT NULL
);

CREATE TABLE [site] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[name] VARCHAR(40)  UNIQUE NOT NULL
);

CREATE TABLE [transponder] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[sid] INTEGER  NOT NULL,
[tag] VARCHAR(20)  NOT NULL,
[note] VARCHAR(40)  NOT NULL
);

CREATE TABLE [weight] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[sid] INTEGER  NOT NULL,
[eid] INTEGER  NOT NULL,
[entry] INTEGER  NOT NULL,
[length] INTEGER  NOT NULL,
[tag] VARCHAR(20)  NOT NULL,
[mean] INTEGER  NOT NULL,
[adjusted] INTEGER  NOT NULL,
[note] VARCHAR(40)  NOT NULL
);

CREATE UNIQUE INDEX [IDX_DATA_EVENT] ON [data](
[sid]  ASC,
[eid]  ASC,
[entry]  ASC
);

CREATE INDEX [IDX_EVENT_TS] ON [event](
[sid]  ASC,
[sdate]  ASC,
[stime]  ASC
);

CREATE UNIQUE INDEX [IDX_TRANSPONDER_TAG] ON [transponder](
[sid]  ASC,
[tag]  ASC
);

CREATE INDEX [IDX_WEIGHT_EVENT] ON [weight](
[sid]  ASC,
[eid]  ASC,
[entry]  ASC
);
